### ISSUE TITLE
💗 the clean and simple look!  How about a screenshots?  

### ISSUE THREAD

**Issue by PySimpleGUI** [brccabral/WeatherPySimpleGUI#1]
I know visitors to your repo will love to see what you've made!

![image](https://user-images.githubusercontent.com/46163555/162693692-658c870a-a3df-457c-98f2-adb804684c0a.png)

I'm impressed it's done without registering for a service and it's 100% a free service.  Very nice!

BTW, You can paste the line of code from this issue into your readme to get a screenshot.

-------------

Two suggestions you may like.  No biggie but thought I would throw them in...

1. Embed your images into your .py file.  You have do few of them
2. Bind the return key to your button - then you can enter the city and the return key

I made a trinket with these changes to show ya what they're like.  Since you've not posted a license, I assume this is a private repo and thus this trinket is not publicly available:

https://trinket.io/pygame/083f940889

The degree doesn't display correctly but that's a trinket problem, not yours.

LOVE WHAT YOU'VE MADE!  Keep on building!  Very inspirational way to start the day!

**Comment by brccabral** [comment]
Hi, the code is not mine, as I stated in my README this is from a YouTube
tutorial https://youtu.be/QeMaWQZllhg, all credits to Clear Code.
Both suggestions are good, pre-load the images and bind Return key. In a
more production app definetily it is worth the improvements, but this is a
tutorial, it was made to be simple. I guess these proposals are not complex
and could be made into the tutorial, but Clear Code didn't do it, I think I
am going to keep it as is so I can revisit the code if I need to recheck
the code.
Kudos to PySimpleGUI, a very nice framework.

**Comment by PySimpleGUI** [comment]
Not a problem at all... as you said it's a suggestion.

It is what I teach in the PySimpleGUI Udemy course, the YouTube videos and in the Demo Programs, so thought I would at least let you know the technique I teach and recommend to users.  I ran into a missing assets problem on my first run.  It's a common problem and one way to get around it is to drop them into the code itself.

Thank you very much for the encouragement! ![image](https://user-images.githubusercontent.com/46163555/162772508-d0755628-f5cb-4876-a5d6-30bb3524e785.png)

Every comment has an impact.
